version: "3.3"

services: 
    web:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        ports: 
            - '30080:80'
        volumes: 
            - ./source:/var/www/html
            - ./logs:/var/log/apache2
