version: "3.2"

services: 
    web:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        ports: 
            - '30081:80'
        volumes: 
            - ./source:/var/www/html
            - ./bot.js:/var/www/bot.js
            - ./bot-cron:/etc/cron.d/bot-cron
            - ./logs:/var/log/apache2
